/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TechRouteImport } from './routes/tech'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PrintQrRouteImport } from './routes/print-qr'
import { Route as MapRouteImport } from './routes/map'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TechRoute = TechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintQrRoute = PrintQrRouteImport.update({
  id: '/print-qr',
  path: '/print-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/impact': typeof ImpactRoute
  '/map': typeof MapRoute
  '/print-qr': typeof PrintQrRoute
  '/research': typeof ResearchRoute
  '/tech': typeof TechRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/impact': typeof ImpactRoute
  '/map': typeof MapRoute
  '/print-qr': typeof PrintQrRoute
  '/research': typeof ResearchRoute
  '/tech': typeof TechRoute
  '/track': typeof TrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/impact': typeof ImpactRoute
  '/map': typeof MapRoute
  '/print-qr': typeof PrintQrRoute
  '/research': typeof ResearchRoute
  '/tech': typeof TechRoute
  '/track': typeof TrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/impact'
    | '/map'
    | '/print-qr'
    | '/research'
    | '/tech'
    | '/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/impact'
    | '/map'
    | '/print-qr'
    | '/research'
    | '/tech'
    | '/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/impact'
    | '/map'
    | '/print-qr'
    | '/research'
    | '/tech'
    | '/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ImpactRoute: typeof ImpactRoute
  MapRoute: typeof MapRoute
  PrintQrRoute: typeof PrintQrRoute
  ResearchRoute: typeof ResearchRoute
  TechRoute: typeof TechRoute
  TrackRoute: typeof TrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech': {
      id: '/tech'
      path: '/tech'
      fullPath: '/tech'
      preLoaderRoute: typeof TechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-qr': {
      id: '/print-qr'
      path: '/print-qr'
      fullPath: '/print-qr'
      preLoaderRoute: typeof PrintQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ImpactRoute: ImpactRoute,
  MapRoute: MapRoute,
  PrintQrRoute: PrintQrRoute,
  ResearchRoute: ResearchRoute,
  TechRoute: TechRoute,
  TrackRoute: TrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
